server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://139.9.114.118:3306/oj_platform?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: liuyi1
    password: Hhh123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  judge0:
    base-url: http://139.9.114.118:2358
    poll-interval-ms: 800
    max-poll-count: 25